### ISSUE TITLE
 Unable to add a source with url `https://github.com/kaltura/playkit-ios-widevine.git` named `kaltura`.

### ISSUE THREAD

**Issue by MukundSonaiya** [kaltura/playkit-ios-samples#7] opened 2017-03-02 15:58 UTC
Hello, 
I am trying to run the demo given at this link : https://github.com/kaltura/playkit-ios-samples.

But, When trying to install the pods I get following error :
"[!] Unable to add a source with url `https://github.com/kaltura/playkit-ios-widevine.git` named `kaltura`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo  @add`."
[screen shot 2017-03-02 at 21 27 09](https://cloud.githubusercontent.com/assets/14259424/23515028/096df364-ff8f-11e6-8184-84c6a5f962c8.png)
](url)

**Comment by freemind-** [comment] 2017-03-02 16:05
+1 I have the same problem!

**Comment by kaltura-hooks** [comment] 2017-03-02 16:08
Hi @MukundSonaiya,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by freemind-** [comment] 2017-03-02 16:16
@kaltura-hooks the issue is simpler than that... we don't have access to https://github.com/kaltura/playkit-ios-widevine.git and this repo is included as a source in the Podfile. I suspect that repo is private for now. Could you please help us. Thanks.

**Comment by MukundSonaiya** [comment] 2017-03-02 16:22
I am trying to get the Kaltura player work  on iOS  Platform. Rest of the details are as per my first comment. That is the only detail I have currently.

**Comment by MukundSonaiya** [comment] 2017-03-02 16:34
Following is the link https://github.com/kaltura/playkit-ios-samples for the samples provided on Github which I am trying to run.

**Comment by MukundSonaiya** [comment] 2017-03-02 16:38
Also the link introduction link https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/iOS_Introduction.html says "Page Not Found"

**Comment by MukundSonaiya** [comment] 2017-03-02 16:55
The link specified in the podfile https://github.com/kaltura/playkit-ios-widevine.git  is not available it says 404 not found can you please check this out and let us know what is to be done to things working.

**Comment by freemind-** [comment] 2017-03-02 18:17
@newmaniese @zoharbabin @itaykinnrot any thoughts?

**Comment by gal-orlanczyk** [comment] 2017-03-02 21:21
@freemind- @MukundSonaiya Hey, 
First of all thanks for report, I will look into it and update you how to run properly when I find the issue.

cc: @ElizaSapir @OrenMe

**Comment by OrenMe** [comment] 2017-03-02 21:53
@freemind, you are correct. Currently this repo is not available publicly.
We will revise our demo accordingly as it doesn't necessarily require the dependency to function.
I can recommend in the meanwhile that you just remove it from the pod file and reinstall.
We will update once we update our sample.

Thanks!

**Comment by freemind-** [comment] 2017-03-02 23:29
Oh thank you very much guys for your support!

**Closed** 2017-03-19 12:29 UTC
